[project]
name = "rag-que"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bcrypt>=4.3.0",
    "beautifulsoup4>=4.13.4",
    "fastapi>=0.115.12",
    "google-cloud-storage>=3.1.0",
    "langchain-community>=0.3.24",
    "langchain-text-splitters>=0.3.8",
    "lxml>=5.4.0",
    "openai>=1.84.0",
    "pyjwt>=2.10.1",
    "pymilvus>=2.5.10",
    "pymongo>=4.13.0",
    "pypdf>=5.6.0",
    "python-dotenv>=1.1.0",
    "python-multipart>=0.0.20",
    "redis>=6.2.0",
    "uvicorn>=0.34.3",
]
